In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/yzta-2026-datathon/sample_submission.csv
/kaggle/input/competitions/yzta-2026-datathon/test_x.csv
/kaggle/input/competitions/yzta-2026-datathon/train.csv

In [2]:
import kagglehub

# Download latest version
path = kagglehub.competition_download('yzta-2026-datathon')

print("Path to competition files:", path)

Path to competition files: /kaggle/input/competitions/yzta-2026-datathon

In [3]:
import os

os.listdir('/kaggle/input/competitions/yzta-2026-datathon')

['sample_submission.csv', 'test_x.csv', 'train.csv']

In [4]:
import os

os.listdir('/kaggle/input')

['competitions']

In [5]:
os.listdir('/kaggle/input/competitions')

['yzta-2026-datathon']

In [6]:
import pandas as pd

train = pd.read_csv('/kaggle/input/competitions/yzta-2026-datathon/train.csv')
test = pd.read_csv('/kaggle/input/competitions/yzta-2026-datathon/test_x.csv')
sample = pd.read_csv('/kaggle/input/competitions/yzta-2026-datathon/sample_submission.csv')

In [7]:
import os

print(os.listdir('/kaggle/input/competitions'))

['yzta-2026-datathon']

In [8]:
train.head()

,id,yas,cinsiyet,meslek,vucut_kitle_indeksi,ulke,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,...,stres_skoru,gunluk_calisma_saati,kronotip,ruh_sagligi_durumu,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,mevsim,gun_tipi,bilissel_performans_skoru
0,1,34,Erkek,Saglik Personeli,31.470103,Cin,14.431210,14.645436,27,7,...,9.922976,10.045274,Sabah insani,Anksiyete ve depresyon,78,18.962436,-0.074140,Sonbahar-Kis,Hafta ici,0.136441
1,2,32,Kadin,Muhendis,30.981394,Amerika,21.771870,27.220360,20,4,...,6.626400,6.319245,Gece insani,Saglikli,76,21.225666,0.942672,Sonbahar-Kis,Hafta ici,5.848312
2,3,39,Erkek,Ev Hanimi,21.533898,Spain,18.178857,25.530104,33,7,...,6.093566,3.824463,Notr,Depresyon,66,18.482409,1.239886,Ilkbahar-Yaz,Hafta sonu,6.828276
3,4,40,Kadin,Egitimci,23.310749,Yeni Zelanda,21.438151,15.891188,21,2,...,3.168185,4.597316,Gece insani,Saglikli,60,21.862235,0.727695,Sonbahar-Kis,Hafta sonu,8.144649
4,5,36,Kadin,NaN,NaN,Portekiz,25.468018,16.356738,21,8,...,7.198574,3.189120,Notr,Anksiyete ve depresyon,74,19.223195,-0.223402,Sonbahar-Kis,Hafta ici,0.431423

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           56000 non-null  int64
 1   yas                          56000 non-null  int64
 2   cinsiyet                     56000 non-null  object
 3   meslek                       54622 non-null  object
 4   vucut_kitle_indeksi          54248 non-null  float64
 5   ulke                         56000 non-null  object
 6   rem_yuzdesi                  56000 non-null  float64
 7   derin_uyku_yuzdesi           56000 non-null  float64
 8   uykuya_dalma_suresi_dk       56000 non-null  int64
 9   gecelik_uyanma_sayisi        56000 non-null  int64
 10  uyku_oncesi_kafein_mg        54537 non-null  float64
 11  uyku_oncesi_ekran_suresi_dk  56000 non-null  int64
 12  gunluk_adim_sayisi           56000 non-null  int64
 13  sekerleme_suresi_dk          56000 non-null  int64
 14  stres_skoru                  54285 non-null  float64
 15  gunluk_calisma_saati         56000 non-null  float64
 16  kronotip                     54032 non-null  object
 17  ruh_sagligi_durumu           54904 non-null  object
 18  dinlenik_nabiz_bpm           56000 non-null  int64
 19  oda_sicakligi_celsius        56000 non-null  float64
 20  hafta_sonu_uyku_farki_saat   56000 non-null  float64
 21  mevsim                       56000 non-null  object
 22  gun_tipi                     56000 non-null  object
 23  bilissel_performans_skoru    56000 non-null  float64
dtypes: float64(9), int64(8), object(7)
memory usage: 10.3+ MB

In [10]:
train.isnull().sum()

id                                0
yas                               0
cinsiyet                          0
meslek                         1378
vucut_kitle_indeksi            1752
ulke                              0
rem_yuzdesi                       0
derin_uyku_yuzdesi                0
uykuya_dalma_suresi_dk            0
gecelik_uyanma_sayisi             0
uyku_oncesi_kafein_mg          1463
uyku_oncesi_ekran_suresi_dk       0
gunluk_adim_sayisi                0
sekerleme_suresi_dk               0
stres_skoru                    1715
gunluk_calisma_saati              0
kronotip                       1968
ruh_sagligi_durumu             1096
dinlenik_nabiz_bpm                0
oda_sicakligi_celsius             0
hafta_sonu_uyku_farki_saat        0
mevsim                            0
gun_tipi                          0
bilissel_performans_skoru         0
dtype: int64

In [11]:
train.describe()

,id,yas,vucut_kitle_indeksi,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,uyku_oncesi_kafein_mg,uyku_oncesi_ekran_suresi_dk,gunluk_adim_sayisi,sekerleme_suresi_dk,stres_skoru,gunluk_calisma_saati,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,bilissel_performans_skoru
count,56000.000000,56000.000000,54248.000000,56000.000000,56000.000000,56000.000000,56000.000000,54537.000000,56000.000000,56000.000000,56000.000000,54285.000000,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000
mean,28000.500000,34.714446,26.273651,20.233500,20.246063,20.107536,3.344929,42.110952,63.511446,7493.197554,15.432875,5.741407,7.156456,66.603214,20.531263,1.199050,5.913096
std,16165.951874,11.052508,4.495138,3.442993,4.300421,8.063278,2.034618,72.154159,44.590737,3462.699361,21.104672,1.624985,3.469731,7.353174,2.903317,0.790899,2.231759
min,1.000000,18.000000,16.000000,10.000000,5.000000,1.000000,0.000000,0.000000,2.000000,500.000000,0.000000,1.000000,0.000000,45.000000,15.000000,-1.000000,0.000000
25%,14000.750000,26.000000,23.175279,17.951724,17.337866,14.000000,2.000000,0.000000,30.000000,5042.000000,0.000000,4.761271,4.765942,62.000000,18.457240,0.660030,4.397431
50%,28000.500000,33.000000,26.225806,20.302218,20.292151,20.000000,3.000000,3.000000,51.000000,7426.000000,2.000000,5.824014,7.360860,67.000000,20.487456,1.202921,6.032249
75%,42000.250000,42.000000,29.321503,22.598180,23.227117,25.000000,5.000000,77.000000,84.000000,9876.000000,30.000000,6.837436,9.684531,72.000000,22.522152,1.743940,7.574980
max,56000.000000,69.000000,45.000000,30.000000,30.000000,58.000000,8.000000,400.000000,180.000000,20000.000000,115.000000,10.000000,18.000000,97.000000,28.000000,3.000000,10.000000

In [12]:
num_cols = [
"vucut_kitle_indeksi",
"uyku_oncesi_kafein_mg",
"stres_skoru"
]

cat_cols = [
"meslek",
"kronotip",
"ruh_sagligi_durumu"
]

for col in num_cols:
    train[col] = train[col].fillna(train[col].median())

for col in cat_cols:
    train[col] = train[col].fillna("Unknown")

In [13]:
train.isnull().sum()

id                             0
yas                            0
cinsiyet                       0
meslek                         0
vucut_kitle_indeksi            0
ulke                           0
rem_yuzdesi                    0
derin_uyku_yuzdesi             0
uykuya_dalma_suresi_dk         0
gecelik_uyanma_sayisi          0
uyku_oncesi_kafein_mg          0
uyku_oncesi_ekran_suresi_dk    0
gunluk_adim_sayisi             0
sekerleme_suresi_dk            0
stres_skoru                    0
gunluk_calisma_saati           0
kronotip                       0
ruh_sagligi_durumu             0
dinlenik_nabiz_bpm             0
oda_sicakligi_celsius          0
hafta_sonu_uyku_farki_saat     0
mevsim                         0
gun_tipi                       0
bilissel_performans_skoru      0
dtype: int64

In [14]:
train["uyku_kalitesi"] = (
    train["rem_yuzdesi"] +
    train["derin_uyku_yuzdesi"] -
    (train["gecelik_uyanma_sayisi"] * 2)
)

train["ekran_kafein_etkisi"] = (
    train["uyku_oncesi_ekran_suresi_dk"] +
    train["uyku_oncesi_kafein_mg"]
)

train["stres_calisma_orani"] = (
    train["stres_skoru"] /
    (train["gunluk_calisma_saati"] + 1)
)

train["aktif_yasam_skoru"] = (
    train["gunluk_adim_sayisi"] -
    train["sekerleme_suresi_dk"]
)

In [15]:
train.columns

Index(['id', 'yas', 'cinsiyet', 'meslek', 'vucut_kitle_indeksi', 'ulke',
       'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk',
       'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg',
       'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi',
       'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati',
       'kronotip', 'ruh_sagligi_durumu', 'dinlenik_nabiz_bpm',
       'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'mevsim',
       'gun_tipi', 'bilissel_performans_skoru', 'uyku_kalitesi',
       'ekran_kafein_etkisi', 'stres_calisma_orani', 'aktif_yasam_skoru'],
      dtype='object')

In [16]:
from sklearn.model_selection import train_test_split

X = train.drop(columns=["bilissel_performans_skoru"])
y = train["bilissel_performans_skoru"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_valid.shape)

(44800, 27)
(11200, 27)

In [17]:
from sklearn.preprocessing import LabelEncoder

cat_cols = [
    'cinsiyet',
    'meslek',
    'ulke',
    'kronotip',
    'ruh_sagligi_durumu',
    'mevsim',
    'gun_tipi'
]

for col in cat_cols:
    le = LabelEncoder()

    X_train[col] = le.fit_transform(X_train[col].astype(str))
    X_valid[col] = le.transform(X_valid[col].astype(str))

In [18]:
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004739 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3966
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 27
[LightGBM] [Info] Start training from score 5.913723
RMSE: 1.2326954399201304

In [19]:
test.columns

Index(['id', 'yas', 'cinsiyet', 'meslek', 'vucut_kitle_indeksi', 'ulke',
       'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk',
       'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg',
       'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi',
       'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati',
       'kronotip', 'ruh_sagligi_durumu', 'dinlenik_nabiz_bpm',
       'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'mevsim',
       'gun_tipi'],
      dtype='object')

In [20]:
X_test = test.copy()

X_test = X_test.reindex(columns=X.columns, fill_value=0)

In [21]:
cat_cols = [
    'cinsiyet',
    'meslek',
    'ulke',
    'kronotip',
    'ruh_sagligi_durumu',
    'mevsim',
    'gun_tipi'
]

for col in cat_cols:

    combined = pd.concat([
        X_train[col],
        X_valid[col],
        X_test[col]
    ]).astype(str)

    combined_encoded, uniques = pd.factorize(combined)

    X_train[col] = combined_encoded[:len(X_train)]
    
    X_valid[col] = combined_encoded[
        len(X_train):len(X_train)+len(X_valid)
    ]

    X_test[col] = combined_encoded[
        len(X_train)+len(X_valid):
    ]

In [22]:
model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003104 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3966
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 27
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(learning_rate=0.05, n_estimators=1000, random_state=42)

In [23]:
preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

RMSE: 1.2363460016216261

In [24]:
test_preds = model.predict(X_test)

In [25]:
submission = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": test_preds
})

submission.to_csv("submission.csv", index=False)

submission.head()

   id  bilissel_performans_skoru
0   1                   3.349691
1   2                   5.532660
2   3                   3.151146
3   4                   4.019111
4   5                   2.778505

In [26]:
submission.to_csv("submission.csv", index=False)

In [27]:
import os

os.listdir("/kaggle/working")

['.virtual_documents', 'submission.csv']

In [28]:
!kaggle competitions submit -c yzta-2026-datathon -f submission.csv -m "final submission"

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7d6f47b3a210>: Failed to resolve 'api.kaggle.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d6f47b3a210>: Failed to resolve 'api.kaggle.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 4, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.12/dist-packages/kaggle/__init__.py", line 10, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 670, in authenticate
    if self._authenticate_with_access_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 728, in _authenticate_with_access_token
    username = self._introspect_token(access_token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 768, in _introspect_token
    response = kaggle.security.oauth_client.introspect_token(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kagglesdk/security/services/oauth_service.py", line 44, in introspect_token
    return self._client.call("security.OAuthService", "IntrospectToken", request, IntrospectTokenResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kagglesdk/kaggle_http_client.py", line 96, in call
    http_response = self._session.send(http_request, **settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d6f47b3a210>: Failed to resolve 'api.kaggle.com' ([Errno -3] Temporary failure in name resolution)"))

In [29]:
importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.feature_importances_
})

importance = importance.sort_values(
    by='importance',
    ascending=False
)

print(importance.head(20))

                        feature  importance
14                  stres_skoru        1961
6                   rem_yuzdesi        1834
23                uyku_kalitesi        1731
19        oda_sicakligi_celsius        1704
20   hafta_sonu_uyku_farki_saat        1637
4           vucut_kitle_indeksi        1586
0                            id        1577
15         gunluk_calisma_saati        1494
7            derin_uyku_yuzdesi        1433
25          stres_calisma_orani        1285
12           gunluk_adim_sayisi        1285
24          ekran_kafein_etkisi        1251
8        uykuya_dalma_suresi_dk        1217
11  uyku_oncesi_ekran_suresi_dk        1206
1                           yas        1192
13          sekerleme_suresi_dk        1134
3                        meslek        1096
18           dinlenik_nabiz_bpm        1024
10        uyku_oncesi_kafein_mg         772
5                          ulke         734

In [30]:
X_train = X_train.drop(columns=["id"])
X_valid = X_valid.drop(columns=["id"])
X_test = X_test.drop(columns=["id"])

In [31]:
model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003072 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3711
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 26
[LightGBM] [Info] Start training from score 5.913723
RMSE: 1.2354406989013977

In [67]:
model = LGBMRegressor(
    n_estimators=5000,
    learning_rate=0.01,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(
    X_train,
    y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric='rmse'
)

preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004888 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3627
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 19
[LightGBM] [Info] Start training from score 5.913723
RMSE: 1.3617809136370587

In [ ]:
print("id" in X_train.columns)

In [ ]:
from sklearn.model_selection import KFold
import numpy as np

kf = KFold(n_splits=5, shuffle=True, random_state=42)

rmse_scores = []

for train_idx, val_idx in kf.split(X_train):

    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model = LGBMRegressor(
        n_estimators=1000,
        learning_rate=0.05,
        random_state=42
    )

    model.fit(X_tr, y_tr)

    preds = model.predict(X_val)

    rmse = np.sqrt(mean_squared_error(y_val, preds))
    rmse_scores.append(rmse)

print("CV RMSE:", np.mean(rmse_scores))

In [ ]:
model = LGBMRegressor(
    n_estimators=3000,
    learning_rate=0.01,
    num_leaves=64,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42
)

In [ ]:
model.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="rmse",
    callbacks=[]
)

In [ ]:
low_importance = importance[importance["importance"] < 500]["feature"].tolist()

X_train.drop(columns=low_importance, inplace=True)
X_valid.drop(columns=low_importance, inplace=True)
X_test.drop(columns=low_importance, inplace=True)

In [ ]:
from catboost import CatBoostRegressor

model = CatBoostRegressor(
    iterations=2000,
    learning_rate=0.03,
    depth=6,
    verbose=200
)

model.fit(X_train, y_train)

preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

In [ ]:
model = LGBMRegressor(
    n_estimators=5000,
    learning_rate=0.01,
    num_leaves=128,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.2,
    reg_lambda=0.2,
    random_state=42
)

In [ ]:
model.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="rmse"
)

In [ ]:
from lightgbm import LGBMRegressor
import numpy as np

In [ ]:
m1 = LGBMRegressor(
    n_estimators=3000,
    learning_rate=0.01,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

In [ ]:
m2 = LGBMRegressor(
    n_estimators=4000,
    learning_rate=0.01,
    num_leaves=128,
    subsample=0.7,
    colsample_bytree=0.7,
    random_state=99
)

In [ ]:
m3 = LGBMRegressor(
    n_estimators=3000,
    learning_rate=0.02,
    num_leaves=80,
    reg_alpha=0.2,
    reg_lambda=0.2,
    random_state=2024
)

In [45]:
m1.fit(X_train, y_train)
m2.fit(X_train, y_train)
m3.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005526 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3692
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 21
[LightGBM] [Info] Start training from score 5.913723
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005462 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3692
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 21
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(learning_rate=0.02, n_estimators=3000, num_leaves=80,
              random_state=2024, reg_alpha=0.2, reg_lambda=0.2)

In [46]:
p1 = m1.predict(X_test)
p2 = m2.predict(X_test)
p3 = m3.predict(X_test)

final_preds = (p1 + p2 + p3) / 3

In [47]:
print([var for var in globals().keys() if "test" in var.lower()])

['test', 'train_test_split', 'X_test', 'test_preds']

In [48]:
print(test.columns)

Index(['id', 'yas', 'cinsiyet', 'meslek', 'vucut_kitle_indeksi', 'ulke',
       'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk',
       'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg',
       'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi',
       'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati',
       'kronotip', 'ruh_sagligi_durumu', 'dinlenik_nabiz_bpm',
       'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'mevsim',
       'gun_tipi'],
      dtype='object')

In [49]:
test_ids = test["id"]

In [50]:
submission = pd.DataFrame({
    "id": test_ids,
    "bilissel_performans_skoru": final_preds
})

In [51]:
submission.to_csv("submission.csv", index=False)
print("submission hazır")

submission hazır

In [52]:
from sklearn.model_selection import KFold
from lightgbm import LGBMRegressor
import numpy as np
import pandas as pd

In [53]:
params = {
    "n_estimators": 2000,
    "learning_rate": 0.01,
    "num_leaves": 64,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "random_state": 42
}

In [54]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

test_preds = np.zeros(len(X_test))
oof_preds = np.zeros(len(X_train))

for fold, (train_idx, val_idx) in enumerate(kf.split(X_train)):

    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model = LGBMRegressor(**params)
    model.fit(X_tr, y_tr)

    oof_preds[val_idx] = model.predict(X_val)
    test_preds += model.predict(X_test) / 5

    print(f"Fold {fold+1} done")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004119 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3680
[LightGBM] [Info] Number of data points in the train set: 35840, number of used features: 21
[LightGBM] [Info] Start training from score 5.917230
Fold 1 done
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004367 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3681
[LightGBM] [Info] Number of data points in the train set: 35840, number of used features: 21
[LightGBM] [Info] Start training from score 5.912897
Fold 2 done
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004258 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3678
[LightGBM] [Info] Number of data points in the train set: 35840, number of used features: 21
[LightGBM] [Info] Start training from score 5.912800
Fold 3 done
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004363 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3683
[LightGBM] [Info] Number of data points in the train set: 35840, number of used features: 21
[LightGBM] [Info] Start training from score 5.910709
Fold 4 done
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004053 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3685
[LightGBM] [Info] Number of data points in the train set: 35840, number of used features: 21
[LightGBM] [Info] Start training from score 5.914981
Fold 5 done

In [55]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_train, oof_preds))
print("CV RMSE:", rmse)

CV RMSE: 1.3098602578232625

In [56]:
submission = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": test_preds
})

submission.to_csv("submission.csv", index=False)
print("Submission ready")

Submission ready

In [57]:
final_model = LGBMRegressor(
    n_estimators=2000,
    learning_rate=0.01,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

final_model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005606 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3692
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 21
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.01, n_estimators=2000,
              num_leaves=64, random_state=42, subsample=0.8)

In [58]:
importance = final_model.feature_importances_
features = X_train.columns

In [59]:
imp_df = pd.DataFrame({
    "feature": features,
    "importance": importance
})

imp_df = imp_df.sort_values(by="importance", ascending=False)

print(imp_df.head(20))

                        feature  importance
12         gunluk_calisma_saati        9142
11                  stres_skoru        9111
4                   rem_yuzdesi        8690
17                uyku_kalitesi        8677
15        oda_sicakligi_celsius        7583
5            derin_uyku_yuzdesi        6630
16   hafta_sonu_uyku_farki_saat        6625
2           vucut_kitle_indeksi        6535
19          stres_calisma_orani        6341
9            gunluk_adim_sayisi        6232
6        uykuya_dalma_suresi_dk        6115
18          ekran_kafein_etkisi        5673
8   uyku_oncesi_ekran_suresi_dk        5422
1                        meslek        5394
10          sekerleme_suresi_dk        4958
0                           yas        4867
14           dinlenik_nabiz_bpm        4231
20            aktif_yasam_skoru        3817
7         uyku_oncesi_kafein_mg        3702
13           ruh_sagligi_durumu        3360

In [60]:
print(len(X_train.columns))
print(len(importance))

21
21

In [61]:
importance = final_model.feature_importances_
features = X_train.columns

imp_df = pd.DataFrame({
    "feature": features,
    "importance": importance
})

imp_df = imp_df.sort_values(by="importance", ascending=False)

print(imp_df)

                        feature  importance
12         gunluk_calisma_saati        9142
11                  stres_skoru        9111
4                   rem_yuzdesi        8690
17                uyku_kalitesi        8677
15        oda_sicakligi_celsius        7583
5            derin_uyku_yuzdesi        6630
16   hafta_sonu_uyku_farki_saat        6625
2           vucut_kitle_indeksi        6535
19          stres_calisma_orani        6341
9            gunluk_adim_sayisi        6232
6        uykuya_dalma_suresi_dk        6115
18          ekran_kafein_etkisi        5673
8   uyku_oncesi_ekran_suresi_dk        5422
1                        meslek        5394
10          sekerleme_suresi_dk        4958
0                           yas        4867
14           dinlenik_nabiz_bpm        4231
20            aktif_yasam_skoru        3817
7         uyku_oncesi_kafein_mg        3702
13           ruh_sagligi_durumu        3360
3                          ulke        2895

In [62]:
drop_cols = [
    "meslek",
    "yas"
]

X_train = X_train.drop(columns=drop_cols)
X_valid = X_valid.drop(columns=drop_cols)
X_test = X_test.drop(columns=drop_cols)

In [63]:
final_model = LGBMRegressor(
    n_estimators=2000,
    learning_rate=0.01,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

final_model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004988 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3627
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 19
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.01, n_estimators=2000,
              num_leaves=64, random_state=42, subsample=0.8)

In [64]:
selected_features = X_train.columns

In [65]:
X_train = X_train[selected_features]
X_valid = X_valid[selected_features]
X_test = X_test[selected_features]

In [68]:
final_model = LGBMRegressor(
    n_estimators=2000,
    learning_rate=0.01,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

final_model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004996 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3627
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 19
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.01, n_estimators=2000,
              num_leaves=64, random_state=42, subsample=0.8)

In [69]:
preds = final_model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

RMSE: 1.3581135837814609

In [70]:
print("X_train_full" in globals())
print("X_valid_full" in globals())
print("X_test_full" in globals())

False
False
False

In [71]:
import os

os.listdir("/kaggle/input")

['competitions']

In [72]:
import os

os.listdir("/kaggle/input/competitions")

['yzta-2026-datathon']

In [73]:
import pandas as pd

train = pd.read_csv("/kaggle/input/competitions/yzta-2026-datathon/train.csv")
test = pd.read_csv("/kaggle/input/competitions/yzta-2026-datathon/test_x.csv")

In [74]:
X = train.drop(columns=["bilissel_performans_skoru"])
y = train["bilissel_performans_skoru"]

X_test = test.copy()

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [77]:
X = train.drop(columns=["bilissel_performans_skoru"])
y = train["bilissel_performans_skoru"]

X_test = test.copy()

In [78]:
X = pd.get_dummies(X)
X_test = pd.get_dummies(X_test)

In [81]:
X, X_test = X.align(X_test, join="left", axis=1, fill_value=0)

In [80]:
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor
import numpy as np
from sklearn.metrics import mean_squared_error

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LGBMRegressor(
    n_estimators=1500,
    learning_rate=0.03,
    random_state=42
)

model.fit(X_train, y_train)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002640 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2983
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 55
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(learning_rate=0.03, n_estimators=1500, random_state=42)

In [82]:
from sklearn.metrics import mean_squared_error
import numpy as np

preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))
print("RMSE:", rmse)

RMSE: 1.2323005833048932

In [101]:
cat_model.fit(X_train, y_train)

CatBoostRegressor(depth=4, iterations=2500, l2_leaf_reg=8, learning_rate=0.03, loss_function='RMSE', random_seed=42, verbose=0)

In [106]:
import os
print(os.listdir("/kaggle/working"))

['.virtual_documents', 'catboost_info', 'submission.csv']

In [112]:
print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)
print("X_test:", X_test.shape)

X_train: (44800, 55)
X_valid: (11200, 55)
X_test: (24000, 55)

In [113]:
print("Feature count:", len(X_train.columns))

print(X_train.columns.tolist())

Feature count: 55
['id', 'yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm', 'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'cinsiyet_Erkek', 'cinsiyet_Kadin', 'meslek_Egitimci', 'meslek_Emekli', 'meslek_Ev Hanimi', 'meslek_Lawyer', 'meslek_Lojistik Calisani', 'meslek_Muhendis', 'meslek_Ogrenci', 'meslek_Saglik Personeli', 'meslek_Satis ve Pazarlama Calisani', 'meslek_Serbest Calisan', 'meslek_Yonetici', 'ulke_Amerika', 'ulke_Arjantin', 'ulke_Cin', 'ulke_Fransa', 'ulke_Guney Kore', 'ulke_Ingiltere', 'ulke_Ispanya', 'ulke_Isvec', 'ulke_Mexico', 'ulke_Netherlands', 'ulke_Portekiz', 'ulke_South Korea', 'ulke_Spain', 'ulke_Sweden', 'ulke_Yeni Zelanda', 'kronotip_Gece insani', 'kronotip_Notr', 'kronotip_Sabah insani', 'ruh_sagligi_durumu_Anksiyete', 'ruh_sagligi_durumu_Anksiyete ve depresyon', 'ruh_sagligi_durumu_Depresyon', 'ruh_sagligi_durumu_Saglikli', 'mevsim_Ilkbahar-Yaz', 'mevsim_Sonbahar-Kis', 'gun_tipi_Hafta ici', 'gun_tipi_Hafta sonu']

In [114]:
print(y_train.min(), y_train.max())

print(y_valid.min(), y_valid.max())

0.0 10.0
0.0 10.0

In [115]:
import numpy as np

print("Normal target örnek:")
print(y_train[:5])

print("\nlog1p(target) örnek:")
print(np.log1p(y_train[:5]))

Normal target örnek:
46496    7.468408
9084     3.970538
50615    6.073296
8293     7.645877
17075    7.380115
Name: bilissel_performans_skoru, dtype: float64

log1p(target) örnek:
46496    2.136343
9084     1.603528
50615    1.956327
8293     2.157083
17075    2.125862
Name: bilissel_performans_skoru, dtype: float64

In [116]:
KFold(

SyntaxError: incomplete input (168320609.py, line 1)

In [119]:
print(type(lgb_model))
print(type(cat_model))

<class 'lightgbm.sklearn.LGBMRegressor'>
<class 'catboost.core.CatBoostRegressor'>

In [120]:
fi = pd.DataFrame({
    "feature": X_train.columns,
    "importance": lgb_model.feature_importances_
})

fi = fi.sort_values(
    by="importance",
    ascending=False
)

print(fi.head(25))

                                      feature  importance
11                                stres_skoru        7338
3                                 rem_yuzdesi        6878
2                         vucut_kitle_indeksi        6873
4                          derin_uyku_yuzdesi        6583
9                          gunluk_adim_sayisi        5928
0                                          id        5717
14                      oda_sicakligi_celsius        5695
12                       gunluk_calisma_saati        5668
15                 hafta_sonu_uyku_farki_saat        5599
8                 uyku_oncesi_ekran_suresi_dk        4961
7                       uyku_oncesi_kafein_mg        4515
5                      uykuya_dalma_suresi_dk        4258
1                                         yas        4127
10                        sekerleme_suresi_dk        3750
13                         dinlenik_nabiz_bpm        3717
6                       gecelik_uyanma_sayisi        2547
53                         gun_tipi_Hafta ici         897
50                ruh_sagligi_durumu_Saglikli         692
51                        mevsim_Ilkbahar-Yaz         683
16                             cinsiyet_Erkek         659
45                              kronotip_Notr         612
49               ruh_sagligi_durumu_Depresyon         557
48  ruh_sagligi_durumu_Anksiyete ve depresyon         450
24                             meslek_Ogrenci         360
18                            meslek_Egitimci         348

In [121]:
lgb_preds = lgb_model.predict(X_valid)

print("Prediction min:", lgb_preds.min())
print("Prediction max:", lgb_preds.max())

print("Target min:", y_valid.min())
print("Target max:", y_valid.max())

Prediction min: -0.32088871983782963
Prediction max: 10.351804999139569
Target min: 0.0
Target max: 10.0

In [122]:
print(oof_lgb[:5])
print(oof_cat[:5])

[0.         0.         0.         0.         2.57897773]
[0. 0. 0. 0. 0.]

In [126]:
print("TRAIN columns:")
print(X_train.columns.tolist())

print("\nTEST columns:")
print(X_test.columns.tolist())

TRAIN columns:
['yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm', 'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'cinsiyet_Erkek', 'cinsiyet_Kadin', 'meslek_Egitimci', 'meslek_Emekli', 'meslek_Ev Hanimi', 'meslek_Lawyer', 'meslek_Lojistik Calisani', 'meslek_Muhendis', 'meslek_Ogrenci', 'meslek_Saglik Personeli', 'meslek_Satis ve Pazarlama Calisani', 'meslek_Serbest Calisan', 'meslek_Yonetici', 'ulke_Amerika', 'ulke_Arjantin', 'ulke_Cin', 'ulke_Fransa', 'ulke_Guney Kore', 'ulke_Ingiltere', 'ulke_Ispanya', 'ulke_Isvec', 'ulke_Mexico', 'ulke_Netherlands', 'ulke_Portekiz', 'ulke_South Korea', 'ulke_Spain', 'ulke_Sweden', 'ulke_Yeni Zelanda', 'kronotip_Gece insani', 'kronotip_Notr', 'kronotip_Sabah insani', 'ruh_sagligi_durumu_Anksiyete', 'ruh_sagligi_durumu_Anksiyete ve depresyon', 'ruh_sagligi_durumu_Depresyon', 'ruh_sagligi_durumu_Saglikli', 'mevsim_Ilkbahar-Yaz', 'mevsim_Sonbahar-Kis', 'gun_tipi_Hafta ici', 'gun_tipi_Hafta sonu']

TEST columns:
['yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm', 'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat', 'cinsiyet_Erkek', 'cinsiyet_Kadin', 'meslek_Egitimci', 'meslek_Emekli', 'meslek_Ev Hanimi', 'meslek_Lawyer', 'meslek_Lojistik Calisani', 'meslek_Muhendis', 'meslek_Ogrenci', 'meslek_Saglik Personeli', 'meslek_Satis ve Pazarlama Calisani', 'meslek_Serbest Calisan', 'meslek_Yonetici', 'ulke_Amerika', 'ulke_Arjantin', 'ulke_Cin', 'ulke_Fransa', 'ulke_Guney Kore', 'ulke_Ingiltere', 'ulke_Ispanya', 'ulke_Isvec', 'ulke_Mexico', 'ulke_Netherlands', 'ulke_Portekiz', 'ulke_South Korea', 'ulke_Spain', 'ulke_Sweden', 'ulke_Yeni Zelanda', 'kronotip_Gece insani', 'kronotip_Notr', 'kronotip_Sabah insani', 'ruh_sagligi_durumu_Anksiyete', 'ruh_sagligi_durumu_Anksiyete ve depresyon', 'ruh_sagligi_durumu_Depresyon', 'ruh_sagligi_durumu_Saglikli', 'mevsim_Ilkbahar-Yaz', 'mevsim_Sonbahar-Kis', 'gun_tipi_Hafta ici', 'gun_tipi_Hafta sonu']

In [127]:
# stres x çalışma
X_train["stres_x_calisma"] = (
    X_train["stres_skoru"] *
    X_train["gunluk_calisma_saati"]
)

X_valid["stres_x_calisma"] = (
    X_valid["stres_skoru"] *
    X_valid["gunluk_calisma_saati"]
)

X_test["stres_x_calisma"] = (
    X_test["stres_skoru"] *
    X_test["gunluk_calisma_saati"]
)

# uyku x ekran
X_train["uyku_x_ekran"] = (
    X_train["derin_uyku_yuzdesi"] *
    X_train["uyku_oncesi_ekran_suresi_dk"]
)

X_valid["uyku_x_ekran"] = (
    X_valid["derin_uyku_yuzdesi"] *
    X_valid["uyku_oncesi_ekran_suresi_dk"]
)

X_test["uyku_x_ekran"] = (
    X_test["derin_uyku_yuzdesi"] *
    X_test["uyku_oncesi_ekran_suresi_dk"]
)

# stres x adım
X_train["stres_x_adim"] = (
    X_train["stres_skoru"] *
    X_train["gunluk_adim_sayisi"]
)

X_valid["stres_x_adim"] = (
    X_valid["stres_skoru"] *
    X_valid["gunluk_adim_sayisi"]
)

X_test["stres_x_adim"] = (
    X_test["stres_skoru"] *
    X_test["gunluk_adim_sayisi"]
)

In [128]:
print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)

(44800, 57)
(11200, 57)
(24000, 57)

In [129]:
from lightgbm import LGBMRegressor

lgb_model = LGBMRegressor(
    n_estimators=2000,
    learning_rate=0.03,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgb_model.fit(X_train, y_train)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007392 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3493
[LightGBM] [Info] Number of data points in the train set: 44800, number of used features: 57
[LightGBM] [Info] Start training from score 5.913723

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, n_estimators=2000,
              num_leaves=64, random_state=42, subsample=0.8)

In [130]:
from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=3000,
    learning_rate=0.02,
    depth=6,
    loss_function="RMSE",
    verbose=0,
    random_seed=42
)

cat_model.fit(X_train, y_train)

CatBoostRegressor(depth=6, iterations=3000, learning_rate=0.02, loss_function='RMSE', random_seed=42, verbose=0)

In [131]:
from sklearn.ensemble import ExtraTreesRegressor

et_model = ExtraTreesRegressor(
    n_estimators=500,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

et_model.fit(X_train, y_train)

ExtraTreesRegressor(max_depth=20, n_estimators=500, n_jobs=-1, random_state=42)

In [132]:
lgb_preds = lgb_model.predict(X_valid)
cat_preds = cat_model.predict(X_valid)
et_preds = et_model.predict(X_valid)

In [133]:
final_preds = (
    0.5 * lgb_preds +
    0.3 * cat_preds +
    0.2 * et_preds
)

In [134]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_valid,
        final_preds
    )
)

print("FINAL RMSE:", rmse)

FINAL RMSE: 1.2279082229832152

In [142]:
final_preds = (
    0.45 * lgb_preds +
    0.35 * cat_preds +
    0.20 * et_preds
)

In [143]:
rmse = np.sqrt(mean_squared_error(y_valid, final_preds))
print(rmse)

1.2268015231873932

In [148]:
final_preds = (
    0.40 * lgb_preds +
    0.40 * cat_preds +
    0.20 * et_preds
)

In [149]:
rmse = np.sqrt(mean_squared_error(y_valid, final_preds))
print(rmse)

1.2258084350821807

In [160]:
final_preds = (
    0.38 * lgb_preds +
    0.42 * cat_preds +
    0.20 * et_preds
)

In [162]:
rmse = np.sqrt(mean_squared_error(y_valid, final_preds))
print(rmse)

1.2254430740461675

In [166]:
submission.to_csv("final.submission.csv", index=False)

In [167]:
import pandas as pd

df = pd.read_csv("final.submission.csv")
print(df.head())
print(df.shape)

   id  bilissel_performans_skoru
0   1                   2.636406
1   2                   4.800973
2   3                   2.006605
3   4                   3.329811
4   5                   1.219709
(24000, 2)